global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/config/prometheus.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus-self-poll-job
    scrape_interval: 8s  
    scrape_timeout: 6s  
    metrics_path: /metrics
    scheme: http
    static_configs:  
    - targets:  
        - localhost:9090 #prometheus address in container
  - job_name: alertmanager-monitoring-job
    static_configs:
    - targets:
        - alertmanager:9093
  - job_name: proxy-orange-api-token-validation-1
    scrape_interval: 8s  
    scrape_timeout: 6s  
    metrics_path: /metrics
    scheme: http
    static_configs:  
    - targets:  
        - pushgateway:9091 #need add u service manually or use pushgateway proxy
  - job_name: postgres-exporter-job
    scrape_interval: 8s  
    scrape_timeout: 6s  
    metrics_path: /metrics
    scheme: http
    static_configs:  
    - targets:  
        - postgres-exporter:9187 #need add u service manually or use pushgateway proxy