global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: proxy-orange-api-token-validation-1
    scrape_interval: 8s  
    scrape_timeout: 6s  
    metrics_path: /metrics
    scheme: http
    static_configs:  
    - targets:  
        - pushgateway:9091 #need add u service manually or use pushgateway proxy