# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Development'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/src/Orange.ApiTokenValidation.Bootstrapper/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/src/Orange.ApiTokenValidation.Bootstrapper/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/src/Tests/Orange.ApiTokenValidation.Domain.Tests/*.csproj'
    testRunTitle: 'Unit'
