//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orange.ApiTokenValidation.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orange.ApiTokenValidation.Domain.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect audience length. Audience length must be between {0} and {1}..
        /// </summary>
        internal static string IncorrectAudienceLength {
            get {
                return ResourceManager.GetString("IncorrectAudienceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect issuer length. Issuer length must be between {0} and {1}..
        /// </summary>
        internal static string IncorrectIssuerLength {
            get {
                return ResourceManager.GetString("IncorrectIssuerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect private key length. Private key length must be between {0} and {1}..
        /// </summary>
        internal static string IncorrectPrivateKeyLength {
            get {
                return ResourceManager.GetString("IncorrectPrivateKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect ttl value. Ttl must be between {0} and {1}..
        /// </summary>
        internal static string IncorrectTtlValue {
            get {
                return ResourceManager.GetString("IncorrectTtlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issuer supplied.
        /// </summary>
        internal static string NoIssuer {
            get {
                return ResourceManager.GetString("NoIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry. Possibly you are not registered.
        /// </summary>
        internal static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token audience error.
        /// </summary>
        internal static string TokenAudienceError {
            get {
                return ResourceManager.GetString("TokenAudienceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is disabled.
        /// </summary>
        internal static string TokenDisabled {
            get {
                return ResourceManager.GetString("TokenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired error.
        /// </summary>
        internal static string TokenExpiredError {
            get {
                return ResourceManager.GetString("TokenExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token issuer can&apos;t be null or empty.
        /// </summary>
        internal static string TokenIssuerCantBeNullOrEmpty {
            get {
                return ResourceManager.GetString("TokenIssuerCantBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token issuer error.
        /// </summary>
        internal static string TokenIssuerError {
            get {
                return ResourceManager.GetString("TokenIssuerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is malformed.
        /// </summary>
        internal static string TokenMalformed {
            get {
                return ResourceManager.GetString("TokenMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token signature error.
        /// </summary>
        internal static string TokenSignatureError {
            get {
                return ResourceManager.GetString("TokenSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token to other audience error.
        /// </summary>
        internal static string TokenToOtherAudienceError {
            get {
                return ResourceManager.GetString("TokenToOtherAudienceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token ttl very large.
        /// </summary>
        internal static string TokenTtlLarge {
            get {
                return ResourceManager.GetString("TokenTtlLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token validation failed.
        /// </summary>
        internal static string TokenValidationError {
            get {
                return ResourceManager.GetString("TokenValidationError", resourceCulture);
            }
        }
    }
}
